services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ~/postgres/p1:/var/lib/postgresql/data
  adminer:
    image: dockette/adminer
    ports:
      - 8080:80